version: '2'

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./db-data:/var/lib
    env_file: .env
    networks:
      - back

  wordpress:
    build: ./app
    links:
      - proxy
      - mariadb:mysql
      - hhvm
    volumes:
      - ./hhvm-data:/var/www
    networks:
      - front
      - back

  hhvm:
    image: yewton/hhvm
    volumes:
      - ./hhvm-data:/var/www
    expose:
      - "9000"
    command: hhvm -m server -d hhvm.server.type=fastcgi -d hhvm.server.port=9000
    env_file: .env
    networks:
      - front
      - back

  proxy:
    build: ./h2o
    volumes:
      - ./hhvm-data:/var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front

networks:
  front:
    driver: bridge
  back:
    driver: bridge
