version: '2'

services:
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env
    networks:
      - back

  wordpress:
    build: ./app
    volumes:
      - hhvm-data:/var/www

  hhvm:
    image: yewton/hhvm
    volumes:
      - hhvm-data:/var/www
    expose:
      - "9000"
    command: hhvm -m server -d hhvm.server.type=fastcgi -d hhvm.server.port=9000
    env_file: .env
    networks:
      - front
      - back

  proxy:
    build: ./h2o
    volumes:
      - hhvm-data:/var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front

volumes:
  hhvm-data:
    driver: local
  db-data:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
